language: java

sudo: required

services:
  - docker

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    
    docker login -u="$QUAY_USERNAME" -p="$QUAY_PASSWORD" quay.io;
    
    
    docker build -t api-gateway:latest api-gateway/target/;
    
    docker tag api-gateway quay.io/microservices-sample/api-gateway:$TRAVIS_BUILD_NUMBER;
    docker tag api-gateway quay.io/microservices-sample/api-gateway:latest;
    
    docker push quay.io/microservices-sample/api-gateway:$TRAVIS_BUILD_NUMBER;
    docker push quay.io/microservices-sample/api-gateway:latest;
    
    
    docker build -t service-one:latest service-one/target/;
    
    docker tag service-one quay.io/microservices-sample/service-one:$TRAVIS_BUILD_NUMBER;
    docker tag service-one quay.io/microservices-sample/service-one:latest;
    
    docker push quay.io/microservices-sample/service-one:$TRAVIS_BUILD_NUMBER;
    docker push quay.io/microservices-sample/service-one:latest;
    
    
    docker build -t service-two:latest service-two/target/;
    
    docker tag service-two quay.io/microservices-sample/service-two:$TRAVIS_BUILD_NUMBER;
    docker tag service-two quay.io/microservices-sample/service-two:latest;
    
    docker push quay.io/microservices-sample/service-two:$TRAVIS_BUILD_NUMBER;
    docker push quay.io/microservices-sample/service-two:latest;
    
    
    docker build -t service-three:latest service-three/target/;
    
    docker tag service-three quay.io/microservices-sample/service-three:$TRAVIS_BUILD_NUMBER;
    docker tag service-three quay.io/microservices-sample/service-three:latest;
    
    docker push quay.io/microservices-sample/service-three:$TRAVIS_BUILD_NUMBER;
    docker push quay.io/microservices-sample/service-three:latest;
    
    
    docker build -t web-application:latest web-application/target/;
    
    docker tag web-application quay.io/microservices-sample/web-application:$TRAVIS_BUILD_NUMBER;
    docker tag web-application quay.io/microservices-sample/web-application:latest;
    
    docker push quay.io/microservices-sample/web-application:$TRAVIS_BUILD_NUMBER;
    docker push quay.io/microservices-sample/web-application:latest;
    
    fi
